#!/usr/bin/env python3
"""Add deep instance pages to the wiki build."""
import json, os

BASE = os.path.dirname(os.path.abspath(__file__))

# Structured instance data from SSH probes
instances = [
    {
        "id": "feno",
        "name": "Feno",
        "host": "34.239.121.19",
        "user": "ubuntu",
        "purpose": "Dedicated Feno venture agents — oral health AI, Smartbrush, provider intelligence",
        "clawapi": "fenoclawapi.shareos.ai",
        "clawapi_port": 8100,
        "clawapi_repo": "fenoclawapi",
        "version": "2026.3.8 (3caab92)",
        "sessions": 25,
        "skills": 59,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-sonnet-4-6",
        "model_fallbacks": ["openai/gpt-5.2"],
        "image_model": "openai/gpt-image-2",
        "providers": {"amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["memory-core", "memory-lancedb", "whatsapp", "camofox-browser", "telegram", "amazon-bedrock", "anthropic", "google", "openai"],
        "disk": "27G / 96G (28%)",
        "ram": "2.9Gi / 30Gi",
        "uptime": "1 week, 2 days",
        "node": "v22.22.0",
        "pm2": ["sharelandclawapi (online)"],
        "workspace_files": {"SOUL.md": 7352, "AGENTS.md": 7776, "MEMORY.md": 15134, "TOOLS.md": 8495, "IDENTITY.md": 2484, "HEARTBEAT.md": 168, "USER.md": 1472},
        "key_skills": ["feno-brand", "feno-agents-routing", "planning-intelligence", "shareos-goals-management", "video-gen-feno", "superdesign", "valuations-prompt", "partnership-discovery", "mission-control", "venture-valuations"],
        "all_skills": "add-auth,add-fireflies-to-meeting,apple-design,attio-crm,autoresearch-shareos,aws-instances,browser-automation,celli-agent-creator,chat-history,domain-lookup,elevenlabs-tts,email-outreach,fal-media,feno-agents-routing,feno-brand,google-sheets,google-workspace,heygen,higgsfield-video,instagram-reader,intra-claw-instance-connect-sync,kt-sync,limitless,loclx-tunnel,md-viewer,mission-control,mongodb,namecheap,notion,openclaw-instances,partnership-discovery,persuasion,planning-intelligence,qmd-search,reddit-reader,remotion-video,remove-unused-sessions,research,reviews-agent,s3-media,scheduling,session-wakeup,shareos-github,shareos-goals-management,shareos-valuation-goals,shirt-logo-placement,superdesign,supermemory,task-monitor,task-receipt,text-to-gui,twilio,twitter-reader,unipile,vapi-voice,venture-valuations,vercel-deploy,video-gen-feno"
    },
    {
        "id": "shareland",
        "name": "Shareland",
        "host": "98.81.222.36",
        "user": "ubuntu",
        "purpose": "Shareland real estate tokenization venture — token exchange, property analytics, investor management",
        "clawapi": "sharelandclawapi.shareos.ai",
        "clawapi_port": 8100,
        "clawapi_repo": "sharelandclawapi",
        "version": "2026.3.8 (3caab92)",
        "sessions": 25,
        "skills": 56,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["moonshotai/kimi-k2.5"],
        "image_model": "openai/gpt-image-2",
        "providers": {"amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["whatsapp", "memory-core", "memory-lancedb", "camofox-browser", "telegram"],
        "disk": "39G / 96G (40%)",
        "ram": "5.4Gi / 30Gi",
        "uptime": "1 week, 2 days",
        "node": "v22.22.0",
        "pm2": [],
        "workspace_files": {"SOUL.md": 4311, "AGENTS.md": 327, "MEMORY.md": 28479, "TOOLS.md": 8694, "IDENTITY.md": 1687, "HEARTBEAT.md": 168, "USER.md": 586},
        "key_skills": ["shareland-goal-audit", "planning-intelligence", "shareos-goals-management", "video-gen-shareland", "celli-agent-creator", "valuations", "domain-lookup"],
        "all_skills": "Shareland-agents-routing,_brand,add-auth,add-fireflies-to-meeting,attio-crm,autoresearch-shareos,aws-instances,aws-s3,camofox,celli-agent-creator,chat-history,cron-scheduler,cross-session-awareness,domain-lookup,elevenlabs-voice,exa-search,fal-ai,gemini-ai,grok-ai,group-handoff,heygen-video-agent,higgsfield,higgsfield-video,image-analysis,instagram-reader,intra-claw-instance-connect-sync,jina-reader,kt-sync,limitless,localxpose,md-viewer,mongodb,namecheap,openai-chat,openclaw-instances,openrouter,perplexity-search,planning-intelligence,qmd-search,reddit-reader,remotion,remove-unused-sessions,retrospective,reviews-agent,session-wakeup,shareos-brainstorm,shareos-github,shareos-goals-management,superdesign,task-monitor,team-contacts,twilio-sms,twitter-reader,uiux-pro-max,unipile,v0-ui,valuations,vapi-voice,vercel-deploy,video-gen-shareland,whatsapp-messaging"
    },
    {
        "id": "instill",
        "name": "instill",
        "host": "44.203.114.96",
        "user": "ec2-user",
        "purpose": "instill culture operating system — AI culture measurement, organizational intelligence, Nike integration",
        "clawapi": "instillclawapi.shareos.ai",
        "clawapi_port": 8100,
        "clawapi_repo": "instillclawapi",
        "version": "2026.3.8 (3caab92)",
        "sessions": 56,
        "skills": 46,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["amazon-bedrock/us.anthropic.claude-sonnet-4-6"],
        "image_model": "openai/gpt-image-2",
        "providers": {"amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["telegram", "camofox-browser", "whatsapp"],
        "disk": "18G / 100G (18%)",
        "ram": "1.8Gi / 30Gi",
        "uptime": "1 week, 2 days",
        "node": "v22.22.0",
        "pm2": ["instillclawapi (online)"],
        "workspace_files": {"SOUL.md": 3078, "AGENTS.md": 23506, "MEMORY.md": 8675, "TOOLS.md": 8694, "IDENTITY.md": 368, "HEARTBEAT.md": 168, "USER.md": 971},
        "key_skills": ["instill-culture-repos", "planning-intelligence", "shareos-goals-management", "video-gen-instill", "clawos-updates", "mission-control"],
        "all_skills": "_brand,add-auth,add-fireflies-to-meeting,attio,autoresearch-shareos,aws-instances,chat-history,clawbot,clawos-updates,domain-lookup,exa,fal-ai,google-workspace,grok-search,heygen,higgsfield,instagram,instill-culture-repos,intra-claw-instance-connect-sync,jina,kt-sync,limitless,loclx,md-viewer,mission-control,mongodb,namecheap,onboarding,openai-agents,openclaw-instances,perplexity,planning-intelligence,qmd,reddit-reader,remove-unused-sessions,reviews-agent,s3-upload,session-wakeup,shareos-goals-management,shareos-repo,superdesign,task-monitor,twilio,twitter-reader,unipile,v0,valuations-prompt,vapi,video-gen-instill"
    },
    {
        "id": "sharehealth",
        "name": "Share Health",
        "host": "3.86.145.38",
        "user": "ec2-user",
        "purpose": "Share Health biological performance venture — health data integration, wellness tracking, competitor monitoring",
        "clawapi": "sharehealthclawapi.shareos.ai",
        "clawapi_port": 8100,
        "clawapi_repo": "sharehealthclawapi",
        "version": "2026.3.8 (3caab92)",
        "sessions": 26,
        "skills": 47,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["amazon-bedrock/us.anthropic.claude-sonnet-4-6"],
        "image_model": "openai/gpt-image-2",
        "providers": {"openrouter": ["openai/gpt-5.2", "openai/gpt-4.1", "google/gemini-3-pro-preview"], "minimax": ["MiniMax-M2.5"], "amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["telegram", "camofox-browser", "whatsapp", "minimax-portal-auth"],
        "disk": "14G / 100G (14%)",
        "ram": "1.4Gi / 30Gi",
        "uptime": "1 week, 2 days",
        "node": "v22.22.0",
        "pm2": ["sharehealthclawapi (online)"],
        "workspace_files": {"SOUL.md": 3129, "AGENTS.md": 17722, "MEMORY.md": 2719, "TOOLS.md": 8694, "IDENTITY.md": 1659, "HEARTBEAT.md": 168, "USER.md": 477},
        "key_skills": ["planning-intelligence", "shareos-goals-management", "video-gen-share-health", "mission-control", "mongodb"],
        "all_skills": "_brand,add-auth,add-fireflies-to-meeting,agent-patterns,attio,autoresearch-shareos,aws-instances,chat-history,dedup-updates,domain-lookup,elevenlabs-voice,exa,fal-ai,github-shareos,google-workspace,grok,heygen,higgsfield,instagram-reader,intra-claw-instance-connect-sync,intra-clawinstance-connect-sync,jina,kt-sync,limitless,loclx-tunnel,md-viewer,mission-control,mongodb,namecheap,onboarding,openclaw-instances,perplexity,planning-intelligence,qmd,reddit-reader,remove-unused-sessions,reviews-agent,s3-upload,session-wakeup,shareos-goals-management,superdesign,task-monitor,twilio,twitter-reader,unipile-instagram,unipile-linkedin,v0,valuations,vapi,video-gen-share-health"
    },
    {
        "id": "shareos",
        "name": "ShareOS (Main)",
        "host": "3.83.68.79",
        "user": "ubuntu",
        "purpose": "Primary orchestration hub — coordinates all ventures, runs master agents, manages cross-venture operations",
        "clawapi": "clawapi.shareos.ai",
        "clawapi_port": 8100,
        "clawapi_repo": "clawapi",
        "version": "2026.4.5 (3e72c03)",
        "sessions": 115,
        "skills": 177,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["amazon-bedrock/us.anthropic.claude-sonnet-4-6"],
        "image_model": "openai/gpt-image-2",
        "providers": {"openrouter": ["openai/gpt-5.2", "openai/gpt-5.4", "moonshotai/kimi-k2"], "minimax": ["MiniMax-M2.5"], "amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1", "us.anthropic.claude-sonnet-4-6"]},
        "plugins": ["whatsapp", "telegram", "openclaw-supermemory", "memory-core", "memory-lancedb", "camofox-browser", "brave", "minimax", "amazon-bedrock", "anthropic", "openai", "google", "xai", "openrouter", "browser"],
        "disk": "122G / 968G (13%)",
        "ram": "2.7Gi / 30Gi",
        "uptime": "1 week, 5 days",
        "node": "v22.22.0",
        "pm2": [],
        "workspace_files": {"SOUL.md": 48506, "AGENTS.md": 27657, "MEMORY.md": 4616, "TOOLS.md": 8747, "IDENTITY.md": 865, "HEARTBEAT.md": 9844, "USER.md": 2623, "DESIGN_RULES.md": 7698},
        "key_skills": ["planning-intelligence", "clawos-daily-sync", "kt-sync", "session-wakeup", "task-monitor", "urgent-email", "meetings", "newsletter-curator", "portfolio-construction", "os-intelligence", "knowledge-rag", "polsia-okara"],
        "all_skills": "177 skills (largest instance)"
    },
    {
        "id": "shareos-meetings",
        "name": "ShareOS Meetings",
        "host": "107.21.143.91",
        "user": "ubuntu",
        "purpose": "Meeting intelligence — Fireflies transcript processing, action item extraction, meeting summaries, real-time meeting listening",
        "clawapi": "clawmeetapi.shareos.ai",
        "clawapi_port": 8200,
        "clawapi_repo": "clawmeetingsapi",
        "version": "2026.3.13 (61d171a)",
        "sessions": 487,
        "skills": 147,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["amazon-bedrock/us.anthropic.claude-sonnet-4-6"],
        "image_model": "none",
        "providers": {"openrouter": ["openai/gpt-5.2", "google/gemini-3-pro-preview"], "minimax": ["MiniMax-M2.5"], "anthropic-bedrock": ["anthropic.claude-opus-4-6-v1", "anthropic.claude-sonnet-4-6"], "amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["whatsapp", "telegram", "openclaw-supermemory", "memory-core", "memory-lancedb", "camofox-browser", "minimax-portal-auth"],
        "disk": "133G / 968G (14%)",
        "ram": "4.5Gi / 30Gi",
        "uptime": "1 week, 2 days",
        "node": "v22.22.0",
        "pm2": [],
        "workspace_files": {"SOUL.md": 46711, "AGENTS.md": 23912, "MEMORY.md": 10955, "TOOLS.md": 8694, "IDENTITY.md": 865, "HEARTBEAT.md": 7941, "USER.md": 2623, "DESIGN_RULES.md": 5993},
        "key_skills": ["meetings", "planning-intelligence", "clawos-daily-sync", "session-wakeup", "kt-sync", "task-monitor", "os-intelligence"],
        "all_skills": "147 skills"
    },
    {
        "id": "hamet",
        "name": "Hamet ClawOS",
        "host": "52.23.208.197",
        "user": "ubuntu",
        "purpose": "CEO personal assistant — Hamet's dedicated AI, handles email triage, calendar, meeting prep, personal research, voice calls",
        "clawapi": "hametclawapi.shareos.ai",
        "clawapi_port": 8200,
        "clawapi_repo": "hametclawapi",
        "version": "2026.3.13 (61d171a)",
        "sessions": 797,
        "skills": 154,
        "channels": ["whatsapp", "telegram", "discord"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["amazon-bedrock/us.anthropic.claude-sonnet-4-6"],
        "image_model": "none",
        "providers": {"openrouter": ["openai/gpt-5.2", "google/gemini-3-pro-preview"], "minimax": ["MiniMax-M2.5"], "amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["whatsapp", "telegram", "openclaw-supermemory", "memory-core", "memory-lancedb", "camofox-browser", "minimax-portal-auth", "discord"],
        "disk": "138G / 968G (15%)",
        "ram": "5.1Gi / 30Gi",
        "uptime": "1 week, 6 days",
        "node": "v22.22.0",
        "pm2": [],
        "workspace_files": {"SOUL.md": 46711, "AGENTS.md": 23426, "MEMORY.md": 92070, "TOOLS.md": 9006, "IDENTITY.md": 865, "HEARTBEAT.md": 7837, "USER.md": 2623, "DESIGN_RULES.md": 5993},
        "key_skills": ["urgent-email", "meetings", "limitless", "planning-intelligence", "knowledge-rag", "os-intelligence", "vapi-voice", "newsletter-curator", "deck-agent", "trading"],
        "all_skills": "154 skills (full fleet)"
    },
    {
        "id": "trevor",
        "name": "Trevor ClawOS",
        "host": "52.73.204.100",
        "user": "ubuntu",
        "purpose": "Trevor's dedicated assistant — personal AI for team member",
        "clawapi": None,
        "clawapi_port": None,
        "clawapi_repo": "clawapi",
        "version": "2026.3.13 (61d171a)",
        "sessions": 498,
        "skills": 146,
        "channels": ["whatsapp", "telegram", "discord"],
        "model_primary": "amazon-bedrock/us.anthropic.claude-opus-4-6-v1",
        "model_fallbacks": ["anthropic/claude-sonnet-4-6", "anthropic/claude-opus-4-6", "openai/gpt-4o", "google/gemini-2.0-flash", "minimax/MiniMax-M2.5"],
        "image_model": "none",
        "providers": {"openrouter": ["openai/gpt-5.2", "google/gemini-3-pro-preview"], "minimax": ["MiniMax-M2.5"], "anthropic-bedrock": ["anthropic.claude-opus-4-6-v1"], "amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["whatsapp", "telegram", "openclaw-supermemory", "memory-core", "memory-lancedb", "camofox-browser", "minimax-portal-auth", "discord"],
        "disk": "124G / 968G (13%)",
        "ram": "4.1Gi / 30Gi",
        "uptime": "1 week",
        "node": "v22.22.0",
        "pm2": [],
        "workspace_files": {"SOUL.md": 4453, "AGENTS.md": 2489, "MEMORY.md": 4077, "TOOLS.md": 13725, "IDENTITY.md": 713, "HEARTBEAT.md": 10729, "USER.md": 2623, "DESIGN_RULES.md": 5993},
        "key_skills": ["planning-intelligence", "session-wakeup", "kt-sync", "task-monitor"],
        "all_skills": "146 skills"
    },
    {
        "id": "sharemind",
        "name": "ShareMind ClawOS",
        "host": "54.87.71.65",
        "user": "ubuntu",
        "purpose": "ShareMind venture — human expertise + agent speed marketplace, expert matching, autonomous task distribution",
        "clawapi": None,
        "clawapi_port": None,
        "clawapi_repo": None,
        "version": "2026.3.13 (61d171a)",
        "sessions": 108,
        "skills": 149,
        "channels": ["whatsapp", "telegram"],
        "model_primary": "unknown (model field empty)",
        "model_fallbacks": ["amazon-bedrock/us.anthropic.claude-sonnet-4-6"],
        "image_model": "openai/gpt-image-2",
        "providers": {"openrouter": ["openai/gpt-5.2", "google/gemini-3-pro-preview"], "anthropic-bedrock": ["anthropic.claude-sonnet-4-20250514-v1:0", "anthropic.claude-opus-4-20250514-v1:0"], "amazon-bedrock": ["us.anthropic.claude-opus-4-6-v1"]},
        "plugins": ["whatsapp", "telegram", "openclaw-supermemory", "memory-core", "memory-lancedb", "camofox-browser", "minimax-portal-auth"],
        "disk": "121G / 968G (13%)",
        "ram": "2.8Gi / 30Gi",
        "uptime": "1 week, 2 days",
        "node": "v22.22.0",
        "pm2": [],
        "workspace_files": {"SOUL.md": 46711, "AGENTS.md": 21060, "MEMORY.md": 89804, "TOOLS.md": 8694, "IDENTITY.md": 865, "HEARTBEAT.md": 7781, "USER.md": 2623, "DESIGN_RULES.md": 5993},
        "key_skills": ["planning-intelligence", "session-wakeup", "sharemind integration"],
        "all_skills": "149 skills"
    },
    {
        "id": "dexter",
        "name": "Dexter ClawOS",
        "host": "54.90.137.8",
        "user": "ubuntu",
        "purpose": "Autonomous financial research agent — stock analysis, fundamentals, SEC filings, market data, trading signals",
        "clawapi": "dextorclawapi.shareos.ai",
        "clawapi_port": None,
        "clawapi_repo": "dextorclawapi",
        "version": "Unknown (SSH timed out)",
        "sessions": 0,
        "skills": 0,
        "channels": [],
        "model_primary": "unknown",
        "model_fallbacks": [],
        "image_model": "unknown",
        "providers": {},
        "plugins": [],
        "disk": "unknown",
        "ram": "unknown",
        "uptime": "unknown (unreachable at probe time)",
        "node": "unknown",
        "pm2": [],
        "workspace_files": {},
        "key_skills": ["dexter", "trading", "openinsider", "chainlink-prices"],
        "all_skills": "Unknown (instance unreachable)"
    }
]

# Save as JSON for the build script to consume
with open(os.path.join(BASE, 'instances_data.json'), 'w') as f:
    json.dump(instances, f, indent=2)

print(f"Saved {len(instances)} instance profiles")
